// frontend/ecom-ui/src/components/layout/Navbar.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Link, NavLink, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { useCart } from '../../context/CartContext';
import { useTheme } from '../../context/ThemeContext';
import './Navbar.css';

export const Navbar = () => {
  const { isLoggedIn, isAdmin, username, logout } = useAuth();
  const { count } = useCart();
  const { isLightMode, toggleTheme } = useTheme();
  const navigate = useNavigate();

  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [accountMenuOpen, setAccountMenuOpen] = useState(false);

  const accountMenuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 20);
    };

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setMenuOpen(false);
        setAccountMenuOpen(false);
      }
    };

    const handleClickOutside = (e: MouseEvent) => {
      if (accountMenuRef.current && !accountMenuRef.current.contains(e.target as Node)) {
        setAccountMenuOpen(false);
      }
    };

    window.addEventListener('scroll', handleScroll);
    document.addEventListener('keydown', handleEscape);
    document.addEventListener('mousedown', handleClickOutside);

    return () => {
      window.removeEventListener('scroll', handleScroll);
      document.removeEventListener('keydown', handleEscape);
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  const closeMenu = () => setMenuOpen(false);

  return (
    <>
      <nav className={`aw-navbar ${scrolled ? 'scrolled' : ''} ${menuOpen ? 'menu-open' : ''}`}>
        <div className="navbar-inner">
          {/* LOGO */}
          <Link to="/" className="navbar-brand" onClick={closeMenu}>
            <div className="brand-icon-wrap">
              <span className="material-icons brand-icon">directions_bike</span>
              <div className="brand-pulse"></div>
            </div>
            <div className="brand-text">
              <span className="brand-name">AdventureWorks</span>
              <span className="brand-name">Bike Store</span>
            </div>
          </Link>

          {/* DESKTOP NAV LINKS */}
          <div className={`nav-links ${menuOpen ? 'open' : ''}`}>
            <NavLink to="/" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={closeMenu}>
              <span className="material-icons nav-link-icon">home</span>
              <span>Home</span>
            </NavLink>
            <NavLink data-testid="nav-products" to="/products" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={closeMenu}>
              <span className="material-icons nav-link-icon">pedal_bike</span>
              <span>Products</span>
            </NavLink>
            {isLoggedIn && (
              <NavLink data-testid="nav-orders" to="/orders" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={closeMenu}>
                <span className="material-icons nav-link-icon">receipt_long</span>
                <span>My Orders</span>
              </NavLink>
            )}
            {isAdmin && (
              <>
                <NavLink data-testid="nav-admin" to="/admin" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={closeMenu}>
                  <span className="material-icons nav-link-icon">admin_panel_settings</span>
                  <span>Admin</span>
                </NavLink>
                <NavLink data-testid="nav-dashboard" to="/dashboard" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={closeMenu}>
                  <span className="material-icons nav-link-icon">insights</span>
                  <span>Dashboard</span>
                </NavLink>
                <NavLink data-testid="nav-cube-insights" to="/cube-insights" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={closeMenu}>
                  <span className="material-icons nav-link-icon">auto_awesome</span>
                  <span>Reseller Insights</span>
                </NavLink>
              </>
            )}
          </div>

          {/* RIGHT ACTIONS */}
          <div className="nav-actions">
            {/* Theme Toggle */}
            <button data-testid="nav-theme-btn" className="nav-theme-btn" onClick={toggleTheme} aria-label="Toggle theme">
              {isLightMode ? <span className="material-icons">dark_mode</span> : <span className="material-icons">light_mode</span>}
            </button>

            {/* Cart */}
            {isLoggedIn && (
              <Link data-testid="nav-cart" to="/cart" className="cart-btn">
                <span className="material-icons">shopping_cart</span>
                <span className="cart-label">Cart</span>
                {count > 0 && <span className="cart-badge">{count}</span>}
              </Link>
            )}

            {/* Account (logged in) */}
            {isLoggedIn ? (
              <div className="relative" ref={accountMenuRef}>
                <button data-testid="nav-account-menu" className="account-btn" onClick={() => setAccountMenuOpen(!accountMenuOpen)}>
                  <div className="avatar">{(username || 'U').charAt(0).toUpperCase()}</div>
                  <span className="account-name">{username || 'Account'}</span>
                  <span className="material-icons chevron">expand_more</span>
                </button>

                {accountMenuOpen && (
                  <div className="absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-card ring-1 ring-black ring-opacity-5 z-50 overflow-hidden" style={{ background: 'var(--bg-card)', border: '1px solid var(--border-glow)' }}>
                    <div className="px-4 py-3 border-b" style={{ borderColor: 'var(--border-subtle)' }}>
                      <p className="text-sm font-medium text-white truncate" style={{ color: 'var(--text-primary)' }}>{username}</p>
                      <p className="text-xs truncate" style={{ color: 'var(--text-muted)' }}>{isAdmin ? 'Administrator' : 'Member'}</p>
                    </div>
                    <div className="py-1">
                      <Link to="/orders" className="flex items-center px-4 py-2 text-sm hover:bg-slate-800 transition-colors" style={{ color: 'var(--text-primary)' }} onClick={() => setAccountMenuOpen(false)}>
                        <span className="material-icons mr-2 text-sm">receipt_long</span>
                        My Orders
                      </Link>
                      <button data-testid="nav-logout" onClick={() => { logout(); setAccountMenuOpen(false); navigate('/'); }} className="flex w-full items-center px-4 py-2 text-sm text-red-400 hover:bg-slate-800 transition-colors text-left">
                        <span className="material-icons mr-2 text-sm">logout</span>
                        Sign Out
                      </button>
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <Link data-testid="nav-login" to="/login" className="btn-login">
                <span className="material-icons">login</span>
                Sign In
              </Link>
            )}

            {/* Mobile hamburger */}
            <button className={`hamburger ${menuOpen ? 'open' : ''}`} onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">
              <span></span>
              <span></span>
              <span></span>
            </button>
          </div>
        </div>

        {/* Mobile Menu Overlay */}
        {menuOpen && <div className="mobile-overlay" onClick={closeMenu}></div>}

        {/* Mobile Menu */}
        <div className={`mobile-menu ${menuOpen ? 'open' : ''}`}>
          <NavLink to="/" className="mobile-nav-link" onClick={closeMenu}>
            <span className="material-icons">home</span> Home
          </NavLink>
          <NavLink to="/products" className="mobile-nav-link" onClick={closeMenu}>
            <span className="material-icons">pedal_bike</span> Products
          </NavLink>
          {isLoggedIn && (
            <>
              <NavLink to="/orders" className="mobile-nav-link" onClick={closeMenu}>
                <span className="material-icons">receipt_long</span> My Orders
              </NavLink>
              <NavLink to="/cart" className="mobile-nav-link" onClick={closeMenu}>
                <span className="material-icons">shopping_cart</span> Cart
                {count > 0 && <span className="mobile-badge">{count}</span>}
              </NavLink>
            </>
          )}
          {isAdmin && (
            <>
              <NavLink to="/admin" className="mobile-nav-link" onClick={closeMenu}>
                <span className="material-icons">admin_panel_settings</span> Admin
              </NavLink>
              <NavLink to="/dashboard" className="mobile-nav-link" onClick={closeMenu}>
                <span className="material-icons">insights</span> Dashboard
              </NavLink>
              <NavLink to="/cube-insights" className="mobile-nav-link" onClick={closeMenu}>
                <span className="material-icons">auto_awesome</span> Reseller Insights
              </NavLink>
            </>
          )}
          <div className="mobile-divider"></div>
          {isLoggedIn ? (
            <button className="mobile-nav-link mobile-logout" onClick={() => { logout(); closeMenu(); navigate('/'); }}>
              <span className="material-icons">logout</span> Sign Out
            </button>
          ) : (
            <Link to="/login" className="mobile-nav-link mobile-login" onClick={closeMenu}>
              <span className="material-icons">login</span> Sign In
            </Link>
          )}
        </div>
      </nav>
    </>
  );
};

// frontend/ecom-ui-angular/src/app/shared/navbar/navbar.component.ts
import { Component, HostListener, OnInit } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AsyncPipe, NgIf } from '@angular/common';
import { AuthService } from '../../core/services/auth.service';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { MatBadgeModule } from '@angular/material/badge';
import { CartService } from '../../core/services/cart.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, NgIf, AsyncPipe, MatButtonModule, MatIconModule, MatMenuModule, MatBadgeModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
  scrolled = false;
  menuOpen = false;
  isLightMode = false;

  constructor(public auth: AuthService, public cart: CartService) {}

  ngOnInit() {
    const savedTheme = localStorage.getItem('theme');
    if (savedTheme === 'light') {
      this.isLightMode = true;
      document.documentElement.setAttribute('data-theme', 'light');
    }
  }

  toggleTheme() {
    this.isLightMode = !this.isLightMode;
    if (this.isLightMode) {
      document.documentElement.setAttribute('data-theme', 'light');
      localStorage.setItem('theme', 'light');
    } else {
      document.documentElement.removeAttribute('data-theme');
      localStorage.setItem('theme', 'dark');
    }
  }

  logout() { this.auth.logout(); }

  toggleMenu() { this.menuOpen = !this.menuOpen; }

  @HostListener('window:scroll')
  onScroll() {
    this.scrolled = window.scrollY > 20;
  }

  @HostListener('document:keydown.escape')
  onEscape() {
    this.menuOpen = false;
  }
}

<nav class="aw-navbar" [class.scrolled]="scrolled" [class.menu-open]="menuOpen">
  <div class="navbar-inner">

    <!-- LOGO -->
    <a class="navbar-brand" routerLink="/" (click)="menuOpen=false">
      <div class="brand-icon-wrap">
        <span class="material-icons brand-icon">directions_bike</span>
        <div class="brand-pulse"></div>
      </div>
      <div class="brand-text">
        <span class="brand-name">AdventureWorks</span>
        <span class="brand-sub">Bike Store</span>
      </div>
    </a>

    <!-- DESKTOP NAV LINKS -->
    <div class="nav-links" [class.open]="menuOpen">
      <a class="nav-link" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact:true}"
        (click)="menuOpen=false" data-testid="nav-home">
        <span class="material-icons nav-link-icon">home</span>
        <span>Home</span>
      </a>
      <a class="nav-link" routerLink="/products" routerLinkActive="active" (click)="menuOpen=false"
        data-testid="nav-products">
        <span class="material-icons nav-link-icon">pedal_bike</span>
        <span>Products</span>
      </a>
      <a class="nav-link" routerLink="/orders" routerLinkActive="active" (click)="menuOpen=false"
        *ngIf="(auth.isLoggedIn$ | async)" data-testid="nav-orders">
        <span class="material-icons nav-link-icon">receipt_long</span>
        <span>My Orders</span>
      </a>
      <a class="nav-link" routerLink="/admin" routerLinkActive="active" (click)="menuOpen=false" *ngIf="auth.isAdmin()"
        data-testid="nav-admin">
        <span class="material-icons nav-link-icon">admin_panel_settings</span>
        <span>Admin</span>
      </a>
      <a class="nav-link" routerLink="/dashboard" routerLinkActive="active" (click)="menuOpen=false"
         *ngIf="auth.isAdmin()" data-testid="nav-dashboard">
        <span class="material-icons nav-link-icon">insights</span>
        <span>Dashboard</span>
      </a>
      <a class="nav-link reseller-btn" routerLink="/cube-insights" routerLinkActive="active" (click)="menuOpen=false"
         *ngIf="auth.isAdmin()" data-testid="nav-reseller-insights">
        <span class="material-icons nav-link-icon">auto_awesome</span>
        <span>Reseller Insights</span>
      </a>
    </div>

    <!-- RIGHT ACTIONS -->
    <div class="nav-actions">
      <!-- Theme Toggle -->
      <button class="nav-theme-btn" (click)="toggleTheme()" aria-label="Toggle theme">
        <mat-icon *ngIf="isLightMode">dark_mode</mat-icon>
        <mat-icon *ngIf="!isLightMode">light_mode</mat-icon>
      </button>

      <!-- Cart -->
      <a routerLink="/cart" class="cart-btn" *ngIf="(auth.isLoggedIn$ | async)" data-testid="nav-cart">
        <span class="material-icons">shopping_cart</span>
        <span class="cart-label">Cart</span>
        <span class="cart-badge" *ngIf="cart.count > 0">{{ cart.count }}</span>
      </a>

      <!-- Account (logged in) -->
      <ng-container *ngIf="(auth.isLoggedIn$ | async); else guestBtns">
        <button class="account-btn" [matMenuTriggerFor]="accountMenu" data-testid="nav-account-menu">
          <div class="avatar">{{ (auth.getUsername() || 'U').charAt(0).toUpperCase() }}</div>
          <span class="account-name">{{ auth.getUsername() || 'Account' }}</span>
          <span class="material-icons chevron">expand_more</span>
        </button>
        <mat-menu #accountMenu="matMenu" class="aw-menu">
          <div class="menu-header">
            <div class="menu-avatar">{{ (auth.getUsername() || 'U').charAt(0).toUpperCase() }}</div>
            <div>
              <div class="menu-username">{{ auth.getUsername() }}</div>
              <div class="menu-role">{{ auth.isAdmin() ? 'Administrator' : 'Member' }}</div>
            </div>
          </div>
          <div class="menu-divider"></div>
          <button mat-menu-item routerLink="/orders" class="menu-item">
            <span class="material-icons">receipt_long</span>
            My Orders
          </button>
          <button mat-menu-item (click)="logout()" class="menu-item menu-item-danger" data-testid="nav-logout">
            <span class="material-icons">logout</span>
            Sign Out
          </button>
        </mat-menu>
      </ng-container>

      <!-- Guest -->
      <ng-template #guestBtns>
        <a routerLink="/login" class="btn-login" data-testid="nav-login">
          <span class="material-icons">login</span>
          Sign In
        </a>
      </ng-template>

      <!-- Mobile hamburger -->
      <button class="hamburger" (click)="toggleMenu()" [class.open]="menuOpen" aria-label="Toggle menu">
        <span></span>
        <span></span>
        <span></span>
      </button>
    </div>
  </div>

  <!-- Mobile Menu Overlay -->
  <div class="mobile-overlay" *ngIf="menuOpen" (click)="menuOpen=false"></div>

  <!-- Mobile Menu -->
  <div class="mobile-menu" [class.open]="menuOpen">
    <a class="mobile-nav-link" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact:true}"
      (click)="menuOpen=false">
      <span class="material-icons">home</span> Home
    </a>
    <a class="mobile-nav-link" routerLink="/products" routerLinkActive="active" (click)="menuOpen=false">
      <span class="material-icons">pedal_bike</span> Products
    </a>
    <a class="mobile-nav-link" routerLink="/orders" routerLinkActive="active" (click)="menuOpen=false"
      *ngIf="(auth.isLoggedIn$ | async)">
      <span class="material-icons">receipt_long</span> My Orders
    </a>
    <a class="mobile-nav-link" routerLink="/cart" routerLinkActive="active" (click)="menuOpen=false"
      *ngIf="(auth.isLoggedIn$ | async)">
      <span class="material-icons">shopping_cart</span> Cart
      <span class="mobile-badge" *ngIf="cart.count > 0">{{ cart.count }}</span>
    </a>
    <a class="mobile-nav-link" routerLink="/admin" routerLinkActive="active" (click)="menuOpen=false"
      *ngIf="auth.isAdmin()">
      <span class="material-icons">admin_panel_settings</span> Admin
    </a>
    <a class="mobile-nav-link" routerLink="/dashboard" routerLinkActive="active" (click)="menuOpen=false"
      *ngIf="auth.isAdmin()">
      <span class="material-icons">insights</span> Dashboard
    </a>
    <a class="mobile-nav-link reseller-btn-mobile" routerLink="/cube-insights" routerLinkActive="active" (click)="menuOpen=false" *ngIf="auth.isAdmin()">
      <span class="material-icons">auto_awesome</span> Reseller Insights
    </a>
    <div class="mobile-divider"></div>
    <ng-container *ngIf="(auth.isLoggedIn$ | async); else mobileGuest">
      <button class="mobile-nav-link mobile-logout" (click)="logout(); menuOpen=false">
        <span class="material-icons">logout</span> Sign Out
      </button>
    </ng-container>
    <ng-template #mobileGuest>
      <a class="mobile-nav-link mobile-login" routerLink="/login" (click)="menuOpen=false">
        <span class="material-icons">login</span> Sign In
      </a>
    </ng-template>
  </div>
</nav>
