// frontend/ecom-ui-angular/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, Validators, FormGroup } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule
  ],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  mode: 'login'|'register' = 'login';
  error = '';
  loading = false;
  showPassword = false;

  form!: FormGroup;

  constructor(
    private fb: FormBuilder,
    private auth: AuthService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.form = this.fb.group({
      username: ['', [Validators.required, Validators.minLength(3)]],
      email: [''],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  get usernameCtrl() { return this.form.get('username'); }
  get passwordCtrl() { return this.form.get('password'); }

  switchMode(m: 'login'|'register') {
    this.mode = m;
    this.error = '';
  }

  submit() {
    if (this.form.invalid) return;
    this.loading = true;
    this.error = '';

    const v = this.form.value;
    const username = (v.username ?? '').trim();
    const password = (v.password ?? '').trim();

    const obs = this.mode === 'login'
      ? this.auth.login({ username, password })
      : this.auth.register({ username, email: (v.email ?? '').trim(), password });

    obs.subscribe({
      next: () => {
        this.loading = false;
        const returnUrl = this.route.snapshot.queryParamMap.get('returnUrl') || '/';
        this.router.navigateByUrl(returnUrl);
      },
      error: (err) => {
        this.loading = false;
        this.error = err?.error ?? err?.message ?? 'Failed';
      }
    });
  }
}
<div class="login-page">

  <!-- Background orbs -->
  <div class="login-orb orb-1"></div>
  <div class="login-orb orb-2"></div>

  <!-- Grid pattern overlay -->
  <div class="login-grid-bg"></div>

  <div class="login-container">

    <!-- Left branding panel -->
    <div class="login-brand-panel">
      <div class="brand-logo">
        <div class="brand-icon-box">
          <span class="material-icons">directions_bike</span>
        </div>
        <div>
          <div class="brand-name">AdventureWorks</div>
          <div class="brand-tagline">Bike Store</div>
        </div>
      </div>
      <h2 class="brand-headline">Your next ride<br><span class="text-gradient">starts here.</span></h2>
      <p class="brand-sub">
        Access your account to manage orders, track your bikes, and explore our premium catalog.
      </p>

      <div class="brand-features">
        <div class="brand-feature">
          <span class="material-icons">check_circle</span>
          <span>500+ premium products</span>
        </div>
        <div class="brand-feature">
          <span class="material-icons">check_circle</span>
          <span>Real-time order tracking</span>
        </div>
        <div class="brand-feature">
          <span class="material-icons">check_circle</span>
          <span>Secure JWT authentication</span>
        </div>
      </div>

      <div class="brand-footer-note">
        Powered by AdventureWorks2019 · ASP.NET Core · Angular 17
      </div>
    </div>

    <!-- Auth form panel -->
    <div class="login-form-panel glass-strong">
      <!-- Mode tabs -->
      <div class="mode-tabs">
        <button class="mode-tab" [class.active]="mode === 'login'" (click)="switchMode('login')" data-testid="mode-login">
          <span class="material-icons">login</span>
          Sign In
        </button>
        <button class="mode-tab" [class.active]="mode === 'register'" (click)="switchMode('register')" data-testid="mode-register">
          <span class="material-icons">person_add</span>
          Create Account
        </button>
      </div>

      <div class="form-header">
        <h1 class="form-title">{{ mode === 'login' ? 'Welcome back' : 'Create your account' }}</h1>
        <p class="form-subtitle">{{ mode === 'login' ? 'Sign in to continue to AdventureWorks' : 'Join thousands of cycling enthusiasts' }}</p>
      </div>

      <form [formGroup]="form" (ngSubmit)="submit()" class="auth-form">

        <div class="form-field">
          <label class="field-label">
            <span class="material-icons">person</span>
            Username
          </label>
          <input
            class="aw-input"
            formControlName="username"
            placeholder="Enter your username"
            data-testid="login-username"
            autocomplete="username"
          />
          <div class="field-error" *ngIf="usernameCtrl?.touched && usernameCtrl?.invalid">
            <span class="material-icons">error</span>
            Username is required
          </div>
        </div>

        <div class="form-field" *ngIf="mode === 'register'">
          <label class="field-label">
            <span class="material-icons">email</span>
            Email
          </label>
          <input
            class="aw-input"
            formControlName="email"
            placeholder="your@email.com"
            type="email"
            data-testid="register-email"
            autocomplete="email"
          />
        </div>

        <div class="form-field">
          <label class="field-label">
            <span class="material-icons">lock</span>
            Password
          </label>
          <div class="password-wrap">
            <input
              class="aw-input"
              [type]="showPassword ? 'text' : 'password'"
              formControlName="password"
              placeholder="Enter your password"
              data-testid="login-password"
              autocomplete="current-password"
            />
            <button type="button" class="toggle-pass" (click)="showPassword = !showPassword">
              <span class="material-icons">{{ showPassword ? 'visibility_off' : 'visibility' }}</span>
            </button>
          </div>
          <div class="field-error" *ngIf="passwordCtrl?.touched && passwordCtrl?.invalid">
            <span class="material-icons">error</span>
            Password is required
          </div>
        </div>

        <!-- Error message -->
        <div class="form-error" *ngIf="error">
          <span class="material-icons">error_outline</span>
          {{ error }}
        </div>

        <!-- Submit -->
        <button
          type="submit"
          class="btn-submit"
          [disabled]="loading || form.invalid"
          data-testid="auth-submit"
        >
          <span class="material-icons" *ngIf="!loading">{{ mode === 'login' ? 'login' : 'person_add' }}</span>
          <span class="spinner" *ngIf="loading"></span>
          {{ loading ? 'Processing...' : (mode === 'login' ? 'Sign In' : 'Create Account') }}
        </button>

      </form>

      <!-- Dev credentials hint -->
      <div class="dev-hint">
        <span class="material-icons">info</span>
        Dev admin: <code>admin</code> / <code>Admin123!</code>
      </div>
    </div>

  </div>
</div>

// frontend/ecom-ui/src/pages/Login/Login.tsx
import React, { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { AuthService } from '../../services/auth';
import './Login.css';

export const Login = () => {
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [username, setUsername] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [touched, setTouched] = useState({ username: false, password: false });

  const navigate = useNavigate();
  const location = useLocation();
  const { login } = useAuth();

  const isInvalid = !username || username.length < 3 || !password || password.length < 6;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (isInvalid) return;
    
    setLoading(true);
    setError('');

    try {
      let data;
      if (mode === 'login') {
        data = await AuthService.login({ username: username.trim(), password: password.trim() });
      } else {
        data = await AuthService.register({ username: username.trim(), email: email.trim(), password: password.trim() });
      }
      
      const adminStatus = data.roles?.includes('Admin') || false;
      login(data.token, adminStatus, data.username);
      
      const params = new URLSearchParams(location.search);
      const returnUrl = params.get('returnUrl') || '/';
      navigate(returnUrl);
    } catch (err: any) {
      setError(err?.response?.data || err?.message || 'Failed');
    } finally {
      setLoading(false);
    }
  };

  const handleBlur = (field: string) => {
    setTouched(prev => ({ ...prev, [field]: true }));
  };

  return (
    <div className="login-page">
      {/* Background orbs */}
      <div className="login-orb orb-1"></div>
      <div className="login-orb orb-2"></div>

      {/* Grid pattern overlay */}
      <div className="login-grid-bg"></div>

      <div className="login-container">
        {/* Left branding panel */}
        <div className="login-brand-panel">
          <div className="brand-logo">
            <div className="brand-icon-box">
              <span className="material-icons">directions_bike</span>
            </div>
            <div>
              <div className="brand-name">AdventureWorks</div>
              <div className="brand-tagline">Bike Store</div>
            </div>
          </div>
          <h2 className="brand-headline">Your next ride<br/><span className="text-gradient">starts here.</span></h2>
          <p className="brand-sub">
            Access your account to manage orders, track your bikes, and explore our premium catalog.
          </p>

          <div className="brand-features">
            <div className="brand-feature">
              <span className="material-icons">check_circle</span>
              <span>500+ premium products</span>
            </div>
            <div className="brand-feature">
              <span className="material-icons">check_circle</span>
              <span>Real-time order tracking</span>
            </div>
            <div className="brand-feature">
              <span className="material-icons">check_circle</span>
              <span>Secure JWT authentication</span>
            </div>
          </div>

          <div className="brand-footer-note">
            Powered by AdventureWorks2019 · ASP.NET Core · React 19
          </div>
        </div>

        {/* Auth form panel */}
        <div className="login-form-panel glass-strong">
          {/* Mode tabs */}
          <div className="mode-tabs">
            <button className={`mode-tab ${mode === 'login' ? 'active' : ''}`} onClick={() => { setMode('login'); setError(''); }}>
              <span className="material-icons">login</span>
              Sign In
            </button>
            <button className={`mode-tab ${mode === 'register' ? 'active' : ''}`} onClick={() => { setMode('register'); setError(''); }}>
              <span className="material-icons">person_add</span>
              Create Account
            </button>
          </div>

          <div className="form-header">
            <h1 className="form-title">{mode === 'login' ? 'Welcome back' : 'Create your account'}</h1>
            <p className="form-subtitle">{mode === 'login' ? 'Sign in to continue to AdventureWorks' : 'Join thousands of cycling enthusiasts'}</p>
          </div>

          <form onSubmit={handleSubmit} className="auth-form">

            <div className="form-field">
              <label className="field-label">
                <span className="material-icons">person</span>
                Username
              </label>
              <input
                className="aw-input"
                value={username}
                onChange={e => setUsername(e.target.value)}
                onBlur={() => handleBlur('username')}
                placeholder="Enter your username"
                autoComplete="username"
              />
              {touched.username && (!username || username.length < 3) && (
                <div className="field-error">
                  <span className="material-icons">error</span>
                  Username must be at least 3 characters
                </div>
              )}
            </div>

            {mode === 'register' && (
              <div className="form-field">
                <label className="field-label">
                  <span className="material-icons">email</span>
                  Email
                </label>
                <input
                  className="aw-input"
                  value={email}
                  onChange={e => setEmail(e.target.value)}
                  placeholder="your@email.com"
                  type="email"
                  autoComplete="email"
                />
              </div>
            )}

            <div className="form-field">
              <label className="field-label">
                <span className="material-icons">lock</span>
                Password
              </label>
              <div className="password-wrap">
                <input
                  className="aw-input"
                  type={showPassword ? 'text' : 'password'}
                  value={password}
                  onChange={e => setPassword(e.target.value)}
                  onBlur={() => handleBlur('password')}
                  placeholder="Enter your password"
                  autoComplete="current-password"
                />
                <button type="button" className="toggle-pass" onClick={() => setShowPassword(!showPassword)}>
                  <span className="material-icons">{showPassword ? 'visibility_off' : 'visibility'}</span>
                </button>
              </div>
              {touched.password && (!password || password.length < 6) && (
                <div className="field-error">
                  <span className="material-icons">error</span>
                  Password must be at least 6 characters
                </div>
              )}
            </div>

            {/* Error message */}
            {error && (
              <div className="form-error">
                <span className="material-icons">error_outline</span>
                {error}
              </div>
            )}

            {/* Submit */}
            <button
              type="submit"
              className="btn-submit"
              disabled={loading || isInvalid}
            >
              {!loading && <span className="material-icons">{mode === 'login' ? 'login' : 'person_add'}</span>}
              {loading && <span className="spinner"></span>}
              {loading ? 'Processing...' : (mode === 'login' ? 'Sign In' : 'Create Account')}
            </button>

          </form>

          {/* Dev credentials hint */}
          <div className="dev-hint">
            <span className="material-icons">info</span>
            Dev admin: <code>admin</code> / <code>Admin123!</code>
          </div>
        </div>

      </div>
    </div>
  );
};
