// frontend/ecom-ui/src/app/pages/my-orders/my-orders.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { OrdersService } from '../../core/services/orders.service';
import { Order } from '../../core/models';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-my-orders',
  standalone: true,
  imports: [CommonModule, RouterLink, MatIconModule],
  templateUrl: './my-orders.component.html',
  styleUrls: ['./my-orders.component.css']
})
export class MyOrdersComponent implements OnInit {
  orders: Order[] = [];
  loading = false;
  error = '';

  constructor(private ordersSvc: OrdersService) {}

  ngOnInit(): void {
    this.loading = true;
    this.ordersSvc.myOrders().subscribe({
      next: rows => { this.orders = rows; this.loading = false; },
      error: err => { this.error = err?.error ?? err?.message ?? 'Failed'; this.loading = false; }
    });
  }

  statusLabel(id: number) {
    return ['Pending','Paid','Processing','Shipped','Delivered','Cancelled'][id] ?? 'Unknown';
  }

  statusIcon(id: number): string {
    switch (id) {
      case 0: return 'schedule';
      case 1: return 'paid';
      case 2: return 'autorenew';
      case 3: return 'local_shipping';
      case 4: return 'check_circle';
      case 5: return 'cancel';
      default: return 'help';
    }
  }

  statusClass(id: number): string {
    switch (id) {
      case 0: return 'status-pending';
      case 1: return 'status-paid';
      case 2: return 'status-processing';
      case 3: return 'status-shipped';
      case 4: return 'status-delivered';
      case 5: return 'status-cancelled';
      default: return 'status-unknown';
    }
  }
}

<div class="orders-page">

  <!-- Page Header -->
  <div class="orders-header">
    <div>
      <div class="aw-badge" style="margin-bottom:0.5rem;">
        <mat-icon style="font-size:12px; height: 12px; width: 12px; line-height: 12px; vertical-align: middle;">receipt_long</mat-icon>
        Order History
      </div>
      <h1 class="orders-title">My Orders</h1>
      <p class="orders-subtitle">Track and review your purchase history.</p>
    </div>
    <a class="btn-secondary-glass" routerLink="/products">
      <mat-icon>pedal_bike</mat-icon>
      Shop More
    </a>
  </div>

  <div class="neon-divider"></div>

  <!-- Loading skeleton -->
  <div class="orders-content" *ngIf="loading">
    <div class="order-skeleton" *ngFor="let i of [1,2,3]">
      <div class="skeleton" style="height:20px;width:30%;margin-bottom:10px;border-radius:4px;"></div>
      <div class="skeleton" style="height:12px;width:20%;margin-bottom:16px;border-radius:4px;"></div>
      <div class="skeleton" style="height:60px;border-radius:8px;"></div>
    </div>
  </div>

  <!-- Error -->
  <div class="orders-empty" *ngIf="error">
    <mat-icon>error_outline</mat-icon>
    <h3>Something went wrong</h3>
    <p>{{ error }}</p>
  </div>

  <!-- Empty state -->
  <div class="orders-empty" *ngIf="!loading && !error && orders.length === 0">
    <mat-icon>shopping_bag</mat-icon>
    <h3>No orders yet</h3>
    <p>Your order history will appear here once you make a purchase.</p>
    <a class="btn-primary-glow" routerLink="/products">
      <mat-icon>pedal_bike</mat-icon>
      Start Shopping
    </a>
  </div>

  <!-- Orders list -->
  <div class="orders-content" *ngIf="!loading && !error && orders.length > 0">
    <div class="order-card gradient-border" *ngFor="let o of orders" data-testid="order-card">

      <!-- Order header -->
      <div class="order-head">
        <div class="order-id-block">
          <div class="order-id">
            <mat-icon class="order-id-icon">receipt</mat-icon>
            Order #{{ o.id }}
          </div>
          <div class="order-date">{{ o.createdAtUtc | date:'MMMM d, y · h:mm a' }}</div>
        </div>

        <div class="order-head-right">
          <div class="order-status-badge" [class]="statusClass(o.status)">
            <mat-icon>{{ statusIcon(o.status) }}</mat-icon>
            {{ statusLabel(o.status) }}
          </div>
          <div class="order-total">
            <span class="order-total-label">Total</span>
            <span class="order-total-value">${{ o.total | number:'1.2-2' }}</span>
          </div>
        </div>
      </div>

      <!-- Order items table -->
      <div class="order-items">
        <div class="order-items-header">
          <span>Product</span>
          <span class="right">Qty</span>
          <span class="right">Unit Price</span>
          <span class="right">Line Total</span>
        </div>
        <div class="order-item-row" *ngFor="let item of o.items">
          <span class="item-name">{{ item.productName }}</span>
          <span class="right item-qty">{{ item.qty }}</span>
          <span class="right item-price">${{ item.unitPrice | number:'1.2-2' }}</span>
          <span class="right item-total">${{ item.lineTotal | number:'1.2-2' }}</span>
        </div>
      </div>

    </div>
  </div>
</div>

// frontend/ecom-ui/src/pages/MyOrders/MyOrders.tsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { OrdersService } from '../../services/orders';
import { Order } from '../../types/models';
import './MyOrders.css';

export const MyOrders = () => {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchOrders = async () => {
      try {
        setLoading(true);
        const data = await OrdersService.myOrders();
        setOrders(data || []);
      } catch (err: any) {
        setError(err?.response?.data || err?.message || 'Failed to load orders');
      } finally {
        setLoading(false);
      }
    };
    fetchOrders();
  }, []);

  const statusLabel = (id: number) => {
    return ['Pending','Paid','Processing','Shipped','Delivered','Cancelled'][id] ?? 'Unknown';
  };

  const statusIcon = (id: number) => {
    switch (id) {
      case 0: return 'schedule';
      case 1: return 'paid';
      case 2: return 'autorenew';
      case 3: return 'local_shipping';
      case 4: return 'check_circle';
      case 5: return 'cancel';
      default: return 'help';
    }
  };

  const statusClass = (id: number) => {
    switch (id) {
      case 0: return 'status-pending';
      case 1: return 'status-paid';
      case 2: return 'status-processing';
      case 3: return 'status-shipped';
      case 4: return 'status-delivered';
      case 5: return 'status-cancelled';
      default: return 'status-unknown';
    }
  };

  const formatDate = (dateString: string) => {
    const d = new Date(dateString);
    return new Intl.DateTimeFormat('en-US', {
      month: 'long', day: 'numeric', year: 'numeric',
      hour: 'numeric', minute: '2-digit', hour12: true
    }).format(d);
  };

  return (
    <div className="orders-page">
      {/* Page Header */}
      <div className="orders-header">
        <div>
          <div className="aw-badge" style={{ marginBottom: '0.5rem' }}>
            <span className="material-icons" style={{ fontSize: '12px', height: '12px', width: '12px', lineHeight: '12px', verticalAlign: 'middle' }}>receipt_long</span>
            Order History
          </div>
          <h1 className="orders-title">My Orders</h1>
          <p className="orders-subtitle">Track and review your purchase history.</p>
        </div>
        <Link className="btn-secondary-glass" to="/products">
          <span className="material-icons">pedal_bike</span>
          Shop More
        </Link>
      </div>

      <div className="neon-divider"></div>

      {/* Loading skeleton */}
      {loading && (
        <div className="orders-content">
          {[1, 2, 3].map(i => (
            <div key={i} className="order-skeleton">
              <div className="skeleton" style={{ height: '20px', width: '30%', marginBottom: '10px', borderRadius: '4px' }}></div>
              <div className="skeleton" style={{ height: '12px', width: '20%', marginBottom: '16px', borderRadius: '4px' }}></div>
              <div className="skeleton" style={{ height: '60px', borderRadius: '8px' }}></div>
            </div>
          ))}
        </div>
      )}

      {/* Error */}
      {error && !loading && (
        <div className="orders-empty">
          <span className="material-icons">error_outline</span>
          <h3>Something went wrong</h3>
          <p>{error}</p>
        </div>
      )}

      {/* Empty state */}
      {!loading && !error && orders.length === 0 && (
        <div className="orders-empty">
          <span className="material-icons">shopping_bag</span>
          <h3>No orders yet</h3>
          <p>Your order history will appear here once you make a purchase.</p>
          <Link className="btn-primary-glow" to="/products">
            <span className="material-icons">pedal_bike</span>
            Start Shopping
          </Link>
        </div>
      )}

      {/* Orders list */}
      {!loading && !error && orders.length > 0 && (
        <div className="orders-content">
          {orders.map(o => (
            <div key={o.id} className="order-card gradient-border">
              {/* Order header */}
              <div className="order-head">
                <div className="order-id-block">
                  <div className="order-id">
                    <span className="material-icons order-id-icon">receipt</span>
                    Order #{o.id}
                  </div>
                  <div className="order-date">{formatDate(o.createdAtUtc)}</div>
                </div>

                <div className="order-head-right">
                  <div className={`order-status-badge ${statusClass(o.status)}`}>
                    <span className="material-icons">{statusIcon(o.status)}</span>
                    {statusLabel(o.status)}
                  </div>
                  <div className="order-total">
                    <span className="order-total-label">Total</span>
                    <span className="order-total-value">${o.total.toFixed(2)}</span>
                  </div>
                </div>
              </div>

              {/* Order items table */}
              <div className="order-items">
                <div className="order-items-header">
                  <span>Product</span>
                  <span className="right">Qty</span>
                  <span className="right">Unit Price</span>
                  <span className="right">Line Total</span>
                </div>
                {o.items?.map((item, idx) => (
                  <div key={idx} className="order-item-row">
                    <span className="item-name">{item.productName}</span>
                    <span className="right item-qty">{item.qty}</span>
                    <span className="right item-price">${item.unitPrice.toFixed(2)}</span>
                    <span className="right item-total">${item.lineTotal.toFixed(2)}</span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
