// frontend/ecom-ui/src/pages/Cart/Cart.tsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useCart, CartItem } from '../../context/CartContext';
import { CatalogService } from '../../services/catalog';
import { OrdersService } from '../../services/orders';
import './Cart.css';

export const Cart = () => {
  const { items, count, total, setQty, remove, clear } = useCart();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const customerID = 1;
  const billToAddressID = 1;
  const shipToAddressID = 1;
  const shipMethodID = 1;

  const handleCheckout = async () => {
    if (items.length === 0) return;
    setLoading(true);
    setError('');

    const payload = {
      items: items.map((i: CartItem) => ({ productId: i.product.id, qty: i.qty })),
      customerID,
      billToAddressID,
      shipToAddressID,
      shipMethodID
    };
    
    try {
      await OrdersService.createOrder(payload);
      clear();
      navigate('/orders');
    } catch (e: any) {
      setError(e?.response?.data || e?.message || 'Checkout failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div>
      <div className="cart-header">
        <div className="header-inner">
          <div>
            <div className="aw-badge" style={{ marginBottom: '0.5rem' }}>
              <span className="material-icons" style={{ fontSize: '12px' }}>shopping_cart</span>
              Your Cart
            </div>
            <h1 className="cart-title">Cart</h1>
            <p className="cart-subtitle">Review your items and checkout.</p>
          </div>
          <button className="btn-danger" onClick={clear} disabled={items.length === 0}>
            <span className="material-icons" style={{ fontSize: '16px', marginRight: '4px', verticalAlign: 'middle' }}>delete_sweep</span>
            <span style={{ verticalAlign: 'middle' }}>Clear</span>
          </button>
        </div>
      </div>
      <div className="neon-divider"></div>

      {error && <div className="error" style={{ margin: '1.5rem clamp(1rem, 4vw, 3rem)' }}>{error}</div>}

      {items.length === 0 ? (
        <div className="glass" style={{ padding: '2rem', margin: '0 clamp(1rem, 4vw, 3rem)', borderRadius: '16px', textAlign: 'center' }}>
          <span className="material-icons" style={{ fontSize: '48px', width: '48px', height: '48px', color: 'var(--text-muted)', marginBottom: '1rem' }}>shopping_cart</span>
          <div style={{ fontSize: '1.25rem', fontWeight: 600, color: 'var(--text-primary)' }}>Your cart is empty.</div>
          <div style={{ marginTop: '1.5rem' }}>
            <Link className="btn-primary-glow" to="/products">Browse products</Link>
          </div>
        </div>
      ) : (
        <div className="cart-grid" style={{ margin: '1.5rem clamp(1rem, 4vw, 3rem)' }}>
          <div className="glass" style={{ padding: '1.5rem', borderRadius: '16px' }}>
            {items.map((i: CartItem) => {
              const imgUrl = CatalogService.imgUrl(i.product.imageFileName);
              return (
                <div key={i.product.id} className="item cart-item">
                  <img className="thumb" src={imgUrl || '/assets/images/default.png'} alt={i.product.name} />
                  <div className="info">
                    <div className="name">{i.product.name}</div>
                    <div className="small text-muted">{i.product.categoryName} / {i.product.subCategoryName}</div>
                    <div className="price text-glow-cyan">${i.product.price.toFixed(2)}</div>
                  </div>
                  <div className="qty">
                    <button className="qty-btn" onClick={() => setQty(i.product.id, i.qty - 1)} disabled={i.qty <= 1}>
                      <span className="material-icons">remove</span>
                    </button>
                    <input 
                      className="aw-input qty-input" 
                      type="number" 
                      value={i.qty} 
                      onChange={(e) => setQty(i.product.id, Number(e.target.value))} 
                      min="1" 
                    />
                    <button className="qty-btn" onClick={() => setQty(i.product.id, i.qty + 1)}>
                      <span className="material-icons">add</span>
                    </button>
                  </div>
                  <div className="lineTotal">${(i.qty * i.product.price).toFixed(2)}</div>
                  <button className="btn-danger-icon" onClick={() => remove(i.product.id)}>
                    <span className="material-icons">delete</span>
                  </button>
                </div>
              );
            })}
          </div>

          <div className="glass summary" style={{ padding: '1.5rem', borderRadius: '16px', alignSelf: 'start' }}>
            <div className="sum-title" style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '1rem' }}>Order Summary</div>
            <div className="sumRow text-muted"><span>Items</span><b>{count}</b></div>
            <div className="sumRow" style={{ fontSize: '1.25rem', color: 'var(--text-primary)', marginTop: '1rem' }}>
              <span>Total</span><b className="text-glow-cyan">${total.toFixed(2)}</b>
            </div>
            <div style={{ margin: '1.5rem 0', borderBottom: '1px solid rgba(255,255,255,0.1)' }}></div>
            <button 
              className="btn-primary-glow" 
              style={{ width: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '0.5rem' }} 
              onClick={handleCheckout} 
              disabled={loading}
            >
              <span className="material-icons">shopping_bag</span>
              Checkout
            </button>
            <div className="small text-muted" style={{ marginTop: '1rem', textAlign: 'center' }}>Creates an order using your account.</div>
          </div>
        </div>
      )}
    </div>
  );
};

// frontend/ecom-ui/src/app/pages/cart/cart.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { Subscription } from 'rxjs';

import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatDividerModule } from '@angular/material/divider';

import { CartService, CartItem } from '../../core/services/cart.service';
import { OrdersService } from '../../core/services/orders.service';
import { CatalogService } from '../../core/services/catalog.service';

@Component({
  selector: 'app-cart',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    MatButtonModule,
    MatCardModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatDividerModule,
  ],
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css']
})
export class CartComponent implements OnInit, OnDestroy {
  items: CartItem[] = [];
  loading = false;
  error = '';
  private sub?: Subscription;

  constructor(
    public cart: CartService,
    private orders: OrdersService,
    private catalog: CatalogService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.sub = this.cart.items$.subscribe(items => this.items = items);
  }

  ngOnDestroy(): void {
    this.sub?.unsubscribe();
  }

  imgUrl(fileName?: string | null) {
    return this.catalog.imgUrl(fileName);
  }

  inc(i: CartItem) { this.cart.setQty(i.product.id, i.qty + 1); }
  dec(i: CartItem) { this.cart.setQty(i.product.id, i.qty - 1); }
  update(i: CartItem, v: any) {
    this.cart.setQty(i.product.id, Number(v));
  }

  customerID = 1;
  billToAddressID = 1;
  shipToAddressID = 1;
  shipMethodID = 1;

  checkout() {
    if (this.items.length === 0) return;
    this.loading = true;
    this.error = '';

    const payload = {
      items: this.items.map(i => ({ productId: i.product.id, qty: i.qty })),
      customerID: this.customerID,
      billToAddressID: this.billToAddressID,
      shipToAddressID: this.shipToAddressID,
      shipMethodID: this.shipMethodID
    };
    
    this.orders.createOrder(payload as any).subscribe({
      next: () => {
        this.cart.clear();
        this.loading = false;
        this.router.navigateByUrl('/orders');
      },
      error: (e) => {
        this.loading = false;
        this.error = e?.error ?? e?.message ?? 'Checkout failed';
      }
    });
  }
}

<div class="cart-header">
  <div class="header-inner">
    <div>
      <div class="aw-badge" style="margin-bottom:0.5rem;">
        <span class="material-icons" style="font-size:12px;">shopping_cart</span>
        Your Cart
      </div>
      <h1 class="cart-title">Cart</h1>
      <p class="cart-subtitle">Review your items and checkout.</p>
    </div>
    <button class="btn-danger" (click)="cart.clear()" [disabled]="items.length===0" data-testid="cart-clear">
      <span class="material-icons" style="font-size: 16px; margin-right: 4px; vertical-align: middle;">delete_sweep</span>
      <span style="vertical-align: middle;">Clear</span>
    </button>
  </div>
</div>
<div class="neon-divider"></div>

<div *ngIf="error" class="error" style="margin: 1.5rem clamp(1rem, 4vw, 3rem);">{{ error }}</div>

<div class="glass" style="padding: 2rem; margin: 0 clamp(1rem, 4vw, 3rem); border-radius: 16px; text-align: center;" *ngIf="items.length===0">
  <mat-icon style="font-size: 48px; width: 48px; height: 48px; color: var(--text-muted); margin-bottom: 1rem;">shopping_cart</mat-icon>
  <div style="font-size: 1.25rem; font-weight: 600; color: var(--text-primary);">Your cart is empty.</div>
  <div style="margin-top:1.5rem;">
    <a class="btn-primary-glow" routerLink="/products">Browse products</a>
  </div>
</div>

<div class="cart-grid" *ngIf="items.length>0" style="margin: 1.5rem clamp(1rem, 4vw, 3rem);">
  <div class="glass" style="padding: 1.5rem; border-radius: 16px;">
    <div class="item cart-item" *ngFor="let i of items">
      <img class="thumb" [src]="imgUrl(i.product.imageFileName)" [alt]="i.product.name" />
      <div class="info">
        <div class="name">{{ i.product.name }}</div>
        <div class="small text-muted">{{ i.product.categoryName }} / {{ i.product.subCategoryName }}</div>
        <div class="price text-glow-cyan">${{ i.product.price | number:'1.2-2' }}</div>
      </div>
      <div class="qty">
        <button class="qty-btn" (click)="dec(i)" [disabled]="i.qty<=1" data-testid="cart-qty-dec"><mat-icon>remove</mat-icon></button>
        <input class="aw-input qty-input" type="number" [ngModel]="i.qty" (ngModelChange)="update(i,$event)" min="1" data-testid="cart-qty-input" />
        <button class="qty-btn" (click)="inc(i)" data-testid="cart-qty-inc"><mat-icon>add</mat-icon></button>
      </div>
      <div class="lineTotal">${{ (i.qty*i.product.price) | number:'1.2-2' }}</div>
      <button class="btn-danger-icon" (click)="cart.remove(i.product.id)" data-testid="cart-remove-item">
        <mat-icon>delete</mat-icon>
      </button>
    </div>
  </div>

  <div class="glass summary" style="padding: 1.5rem; border-radius: 16px; align-self: start;">
    <div class="sum-title" style="font-size:1.25rem; font-weight:700; margin-bottom: 1rem;">Order Summary</div>
    <div class="sumRow text-muted"><span>Items</span><b>{{ cart.count }}</b></div>
    <div class="sumRow" style="font-size: 1.25rem; color: var(--text-primary); margin-top: 1rem;"><span>Total</span><b class="text-glow-cyan">${{ cart.total | number:'1.2-2' }}</b></div>
    <div style="margin:1.5rem 0; border-bottom: 1px solid rgba(255,255,255,0.1);"></div>
    <button class="btn-primary-glow" style="width: 100%; display: flex; justify-content: center; align-items: center; gap: 0.5rem;" (click)="checkout()" [disabled]="loading" data-testid="cart-checkout">
      <mat-icon>shopping_bag</mat-icon>
      Checkout
    </button>
    <div class="small text-muted" style="margin-top:1rem; text-align: center;">Creates an order using your account.</div>
  </div>
</div>
