// frontend/ecom-ui/src/pages/AdminDashboard/AdminDashboard.tsx
import React, { useState, useEffect } from 'react';
import { CatalogService } from '../../services/catalog';
import { OrdersService } from '../../services/orders';
import { Category, SubCategory, Product, Order } from '../../types/models';
import './AdminDashboard.css';

const STATUSES = [
  { id: 0, label: 'Pending', icon: 'schedule' },
  { id: 1, label: 'Paid', icon: 'paid' },
  { id: 2, label: 'Processing', icon: 'autorenew' },
  { id: 3, label: 'Shipped', icon: 'local_shipping' },
  { id: 4, label: 'Delivered', icon: 'check_circle' },
  { id: 5, label: 'Cancelled', icon: 'cancel' },
];

export const AdminDashboard = () => {
  const [activeTab, setActiveTab] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const [categories, setCategories] = useState<Category[]>([]);
  const [subCategories, setSubCategories] = useState<SubCategory[]>([]);
  const [products, setProducts] = useState<Product[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);

  // Search Filters
  const [catFilter, setCatFilter] = useState('');
  const [subFilter, setSubFilter] = useState('');
  const [prodFilter, setProdFilter] = useState('');

  useEffect(() => {
    reloadAll();
  }, []);

  const reloadAll = async () => {
    setLoading(true);
    setError('');
    try {
      const [cats, subs, prods, ords] = await Promise.all([
        CatalogService.getCategories(),
        CatalogService.getSubCategories(),
        CatalogService.getProducts(),
        OrdersService.allOrders()
      ]);
      setCategories(cats || []);
      setSubCategories(subs || []);
      setProducts(prods || []);
      setOrders(ords || []);
    } catch (e: any) {
      setError(e?.response?.data || e?.message || 'Failed to load data');
    } finally {
      setLoading(false);
    }
  };

  // ---- Categories ----
  const handleNewCategory = async () => {
    const name = window.prompt('Enter new category name:');
    if (!name) return;
    try {
      await CatalogService.createCategory(name);
      reloadAll();
    } catch (e: any) { setError(e.message); }
  };
  const handleEditCategory = async (c: Category) => {
    const name = window.prompt('Edit category name:', c.name);
    if (!name || name === c.name) return;
    try {
      await CatalogService.updateCategory(c.id, name);
      reloadAll();
    } catch (e: any) { setError(e.message); }
  };
  const handleDeleteCategory = async (c: Category) => {
    if (!window.confirm(`Delete category "${c.name}"?`)) return;
    try {
      await CatalogService.deleteCategory(c.id);
      reloadAll();
    } catch (e: any) { setError(e.message); }
  };

  // ---- SubCategories ----
  const handleNewSubCategory = async () => {
    const name = window.prompt('Enter new sub-category name:');
    if (!name) return;
    const catIdStr = window.prompt(`Enter category ID for "${name}":\n` + categories.map(c => `${c.id} - ${c.name}`).join('\n'));
    const catId = Number(catIdStr);
    if (!catId) return;
    try {
      await CatalogService.createSubCategory(name, catId);
      reloadAll();
    } catch (e: any) { setError(e.message); }
  };
  const handleEditSubCategory = async (s: SubCategory) => {
    const name = window.prompt('Edit sub-category name:', s.name);
    if (!name) return;
    const catIdStr = window.prompt(`Enter category ID for "${name}":\n` + categories.map(c => `${c.id} - ${c.name}`).join('\n'), String(s.categoryId));
    const catId = Number(catIdStr);
    if (!catId) return;
    try {
      await CatalogService.updateSubCategory(s.id, name, catId);
      reloadAll();
    } catch (e: any) { setError(e.message); }
  };
  const handleDeleteSubCategory = async (s: SubCategory) => {
    if (!window.confirm(`Delete sub-category "${s.name}"?`)) return;
    try {
      await CatalogService.deleteSubCategory(s.id);
      reloadAll();
    } catch (e: any) { setError(e.message); }
  };

  // ---- Products ----
  const handleDeleteProduct = async (p: Product) => {
    if (!window.confirm(`Delete product "${p.name}"?`)) return;
    try {
      await CatalogService.deleteProduct(p.id);
      reloadAll();
    } catch (e: any) { setError(e.message); }
  };

  // ---- Orders ----
  const handleOrderStatus = async (o: Order, newStatus: number) => {
    try {
      await OrdersService.updateStatus(o.id, newStatus);
      reloadAll();
    } catch (e: any) { setError(e.message); }
  };

  const getStatusBadge = (id: number) => {
    switch (id) {
      case 0: return 'badge-pending';
      case 1: return 'badge-paid';
      case 2: return 'badge-processing';
      case 3: return 'badge-shipped';
      case 4: return 'badge-delivered';
      case 5: return 'badge-cancelled';
      default: return '';
    }
  };

  const fmtMoney = (v: number) => new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(v);

  // Filtered lists
  const filteredCats = categories.filter(c => c.name.toLowerCase().includes(catFilter.toLowerCase()));
  const filteredSubs = subCategories.filter(s => s.name.toLowerCase().includes(subFilter.toLowerCase()));
  const filteredProds = products.filter(p => p.name.toLowerCase().includes(prodFilter.toLowerCase()) || p.sku?.toLowerCase().includes(prodFilter.toLowerCase()));

  return (
    <div className="admin-page">
      <div className="admin-header">
        <div>
          <div className="aw-badge" style={{ marginBottom: '0.5rem' }}>
            <span className="material-icons" style={{ fontSize: '12px' }}>admin_panel_settings</span>
            Admin
          </div>
          <h1 className="admin-title">Admin Dashboard</h1>
          <p className="admin-subtitle">Manage catalog, orders, and store settings.</p>
        </div>
        <div>
          <button className="btn-secondary-glass" onClick={reloadAll} disabled={loading}>
            <span className="material-icons" style={{ marginRight: '6px' }}>refresh</span>
            Refresh
          </button>
        </div>
      </div>

      <div className="admin-body">
        {loading && <div className="admin-loading"><span className="material-icons rotating">sync</span> Loading data...</div>}
        {error && <div className="admin-error"><span className="material-icons">error_outline</span> {error}</div>}

        <div className="admin-tabs">
          {['Categories', 'Sub-categories', 'Products', 'Orders'].map((name, i) => {
            const icons = ['category', 'account_tree', 'pedal_bike', 'receipt_long'];
            return (
              <button key={i} className={`admin-tab ${activeTab === i ? 'active' : ''}`} onClick={() => setActiveTab(i)}>
                <span className="material-icons">{icons[i]}</span>
                {name}
              </button>
            );
          })}
        </div>

        {/* CATEGORIES */}
        <div className={`admin-section ${activeTab === 0 ? 'visible' : ''}`}>
          <div className="admin-card">
            <div className="admin-card-head">
              <h3 className="admin-card-title"><span className="material-icons">category</span> Categories</h3>
              <button className="btn-primary-glow" onClick={handleNewCategory}><span className="material-icons">add</span> New</button>
            </div>
            <div className="admin-filters">
              <div className="admin-search-wrap">
                <span className="material-icons admin-search-icon">search</span>
                <input className="aw-input admin-search" value={catFilter} onChange={e => setCatFilter(e.target.value)} placeholder="Search..." />
              </div>
            </div>
            <div className="admin-table-wrap">
              <table className="admin-table">
                <thead><tr><th>Name</th><th></th></tr></thead>
                <tbody>
                  {filteredCats.map(c => (
                    <tr key={c.id}>
                      <td className="name-cell">{c.name}</td>
                      <td style={{ textAlign: 'right' }}>
                        <button className="tbl-btn" onClick={() => handleEditCategory(c)}><span className="material-icons">edit</span> Edit</button>
                        <button className="tbl-btn tbl-btn-danger" onClick={() => handleDeleteCategory(c)} style={{ marginLeft: '6px' }}><span className="material-icons">delete</span> Del</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* SUB-CATEGORIES */}
        <div className={`admin-section ${activeTab === 1 ? 'visible' : ''}`}>
          <div className="admin-card">
            <div className="admin-card-head">
              <h3 className="admin-card-title"><span className="material-icons">account_tree</span> Sub-categories</h3>
              <button className="btn-primary-glow" onClick={handleNewSubCategory}><span className="material-icons">add</span> New</button>
            </div>
            <div className="admin-filters">
              <div className="admin-search-wrap">
                <span className="material-icons admin-search-icon">search</span>
                <input className="aw-input admin-search" value={subFilter} onChange={e => setSubFilter(e.target.value)} placeholder="Search..." />
              </div>
            </div>
            <div className="admin-table-wrap">
              <table className="admin-table">
                <thead><tr><th>Name</th><th>Category ID</th><th></th></tr></thead>
                <tbody>
                  {filteredSubs.map(s => (
                    <tr key={s.id}>
                      <td className="name-cell">{s.name}</td>
                      <td>{s.categoryId}</td>
                      <td style={{ textAlign: 'right' }}>
                        <button className="tbl-btn" onClick={() => handleEditSubCategory(s)}><span className="material-icons">edit</span> Edit</button>
                        <button className="tbl-btn tbl-btn-danger" onClick={() => handleDeleteSubCategory(s)} style={{ marginLeft: '6px' }}><span className="material-icons">delete</span> Del</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* PRODUCTS */}
        <div className={`admin-section ${activeTab === 2 ? 'visible' : ''}`}>
          <div className="admin-card">
            <div className="admin-card-head">
              <h3 className="admin-card-title"><span className="material-icons">pedal_bike</span> Products</h3>
              <button className="btn-primary-glow" onClick={() => window.alert('Use API directly or implement Product Dialog')}><span className="material-icons">add</span> New Product</button>
            </div>
            <div className="admin-filters">
              <div className="admin-search-wrap">
                <span className="material-icons admin-search-icon">search</span>
                <input className="aw-input admin-search" value={prodFilter} onChange={e => setProdFilter(e.target.value)} placeholder="SKU / Name..." />
              </div>
            </div>
            <div className="admin-table-wrap">
              <table className="admin-table">
                <thead><tr><th>SKU</th><th>Name</th><th>Category ID</th><th>Sub ID</th><th style={{ textAlign: 'right' }}>Price</th><th style={{ textAlign: 'right' }}>Stock</th><th></th></tr></thead>
                <tbody>
                  {filteredProds.map(p => (
                    <tr key={p.id}>
                      <td className="mono">{p.sku}</td>
                      <td className="name-cell">{p.name}</td>
                      <td>{p.categoryId}</td>
                      <td>{p.subCategoryId}</td>
                      <td className="price-cell" style={{ textAlign: 'right' }}>{fmtMoney(p.price)}</td>
                      <td className={`stock-cell ${p.stockQty > 50 ? 'stock-high' : p.stockQty > 0 ? 'stock-low' : 'stock-zero'}`} style={{ textAlign: 'right' }}>{p.stockQty}</td>
                      <td style={{ textAlign: 'right' }}>
                        <button className="tbl-btn" onClick={() => window.alert('Edit feature requires full product form.')}><span className="material-icons">edit</span> Edit</button>
                        <button className="tbl-btn tbl-btn-danger" onClick={() => handleDeleteProduct(p)} style={{ marginLeft: '6px' }}><span className="material-icons">delete</span> Del</button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* ORDERS */}
        <div className={`admin-section ${activeTab === 3 ? 'visible' : ''}`}>
          <div className="admin-card">
            <div className="admin-card-head">
              <h3 className="admin-card-title"><span className="material-icons">receipt_long</span> All Orders</h3>
            </div>
            <div className="admin-table-wrap">
              <table className="admin-table">
                <thead><tr><th>#</th><th>Date</th><th>Status</th><th style={{ textAlign: 'right' }}>Total</th><th>Change Status</th></tr></thead>
                <tbody>
                  {orders.map(o => {
                    const statusObj = STATUSES.find(s => s.id === o.status) || STATUSES[0];
                    return (
                      <tr key={o.id}>
                        <td className="mono">{o.id}</td>
                        <td>{new Date(o.createdAtUtc).toLocaleDateString()}</td>
                        <td>
                          <span className={`order-badge ${getStatusBadge(o.status)}`}>
                            <span className="material-icons">{statusObj.icon}</span> {statusObj.label}
                          </span>
                        </td>
                        <td className="price-cell" style={{ textAlign: 'right' }}>{fmtMoney(o.total)}</td>
                        <td>
                          <select className="aw-select admin-select" value={o.status} onChange={e => handleOrderStatus(o, Number(e.target.value))}>
                            {STATUSES.map(s => <option key={s.id} value={s.id}>{s.label}</option>)}
                          </select>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};

// frontend/ecom-ui/src/app/pages/admin-dashboard/admin-dashboard.component.ts
import { Component, OnInit, ViewChild, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { CatalogService } from '../../core/services/catalog.service';
import { OrdersService } from '../../core/services/orders.service';
import { Category, SubCategory, Product, Order } from '../../core/models';

import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatIconModule } from '@angular/material/icon';
import { MatSelectModule } from '@angular/material/select';
import { MatTabsModule } from '@angular/material/tabs';
import { MatChipsModule } from '@angular/material/chips';

import { MatTableModule } from '@angular/material/table';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSort, MatSortModule } from '@angular/material/sort';

import { ConfirmDialogComponent } from '../../shared/dialogs/confirm-dialog.component';
import { ProductEditDialogComponent } from './product-edit-dialog.component';
import { SimpleNameDialogComponent } from './simple-name-dialog.component';
import { OrderTicketDialogComponent } from './order-ticket-dialog.component';

const STATUSES: { id: number; label: string; icon: string }[] = [
  { id: 0, label: 'Pending', icon: 'schedule' },
  { id: 1, label: 'Paid', icon: 'paid' },
  { id: 2, label: 'Processing', icon: 'autorenew' },
  { id: 3, label: 'Shipped', icon: 'local_shipping' },
  { id: 4, label: 'Delivered', icon: 'check_circle' },
  { id: 5, label: 'Cancelled', icon: 'cancel' },
];

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,

    MatButtonModule,
    MatCardModule,
    MatDialogModule,
    MatIconModule,
    MatSelectModule,
    MatTabsModule,
    MatChipsModule,

    MatTableModule,
    MatPaginatorModule,
    MatFormFieldModule,
    MatInputModule,
    MatSortModule,
  ],
  templateUrl: './admin-dashboard.component.html',
  styleUrls: ['./admin-dashboard.component.css']
})
export class AdminDashboardComponent implements OnInit, AfterViewInit {
  categories: Category[] = [];
  subCategories: SubCategory[] = [];
  products: Product[] = [];
  orders: Order[] = [];

  statuses = STATUSES;

  loading = false;
  error = '';

  // ====== MAT TABLE DATASOURCES ======
  catsDs = new MatTableDataSource<Category>([]);
  subsDs = new MatTableDataSource<SubCategory>([]);
  prodsDs = new MatTableDataSource<Product>([]);

  // columns
  catsCols = ['name', 'actions'];
  subsCols = ['name', 'categoryName', 'actions'];
  prodsCols = ['sku', 'name', 'categoryName', 'subCategoryName', 'price', 'stockQty', 'actions'];

  // ====== FILTER STATES ======
  catFilter = '';

  subTextFilter = '';
  subCategoryIdFilter: number | '' = '';

  prodTextFilter = '';
  prodCategoryIdFilter: number | '' = '';
  prodSubCategoryIdFilter: number | '' = '';

  // ====== PAGINATORS ======
  @ViewChild('catsPaginator') catsPaginator!: MatPaginator;
  @ViewChild('subsPaginator') subsPaginator!: MatPaginator;
  @ViewChild('prodsPaginator') prodsPaginator!: MatPaginator;

  // ====== SORTS ======
  @ViewChild('catsSort') catsSort!: MatSort;
  @ViewChild('subsSort') subsSort!: MatSort;
  @ViewChild('prodsSort') prodsSort!: MatSort;

  constructor(
    private catalog: CatalogService,
    private ordersSvc: OrdersService,
    private dialog: MatDialog
  ) {}

  ngOnInit(): void {
    // Multi-field filters
    this.subsDs.filterPredicate = (row: SubCategory, filterJson: string) => {
      const f = JSON.parse(filterJson) as { text: string; categoryId: number | null };
      const t = (f.text || '').toLowerCase();

      const textOk =
        !t ||
        (row.name ?? '').toLowerCase().includes(t) ||
        (row.categoryName ?? '').toLowerCase().includes(t);

      const catOk = f.categoryId == null || row.categoryId === f.categoryId;

      return textOk && catOk;
    };

    this.prodsDs.filterPredicate = (row: Product, filterJson: string) => {
      const f = JSON.parse(filterJson) as { text: string; categoryId: number | null; subCategoryId: number | null };
      const t = (f.text || '').toLowerCase();

      const textOk =
        !t ||
        (row.sku ?? '').toLowerCase().includes(t) ||
        (row.name ?? '').toLowerCase().includes(t) ||
        (row.categoryName ?? '').toLowerCase().includes(t) ||
        (row.subCategoryName ?? '').toLowerCase().includes(t);

      const catOk = f.categoryId == null || row.categoryId === f.categoryId;
      const subOk = f.subCategoryId == null || row.subCategoryId === f.subCategoryId;

      return textOk && catOk && subOk;
    };

    this.reloadAll();
  }

  ngAfterViewInit(): void {
    // attach once view is ready
    this.catsDs.paginator = this.catsPaginator;
    this.subsDs.paginator = this.subsPaginator;
    this.prodsDs.paginator = this.prodsPaginator;

    this.catsDs.sort = this.catsSort;
    this.subsDs.sort = this.subsSort;
    this.prodsDs.sort = this.prodsSort;
  }

  reloadAll() {
    this.loading = true;
    this.error = '';

    Promise.all([
      this.catalog.getCategories().toPromise(),
      this.catalog.getSubCategories().toPromise(),
      this.catalog.getProducts().toPromise(),
      this.ordersSvc.allOrders().toPromise()
    ])
      .then(([cats, subs, prods, orders]) => {
        this.categories = cats ?? [];
        this.subCategories = subs ?? [];
        this.products = prods ?? [];
        this.orders = orders ?? [];

        // push into tables
        this.catsDs.data = this.categories;
        this.subsDs.data = this.subCategories;
        this.prodsDs.data = this.products;

        // re-apply filters after refresh
        this.applyCatFilter();
        this.applySubFilter();
        this.applyProdFilter();

        this.loading = false;
      })
      .catch(err => {
        this.error = err?.error ?? err?.message ?? 'Failed';
        this.loading = false;
      });
  }

  // ===================== FILTER ACTIONS =====================
  applyCatFilter() {
    const v = (this.catFilter || '').trim().toLowerCase();
    this.catsDs.filter = v;
    this.catsDs.paginator?.firstPage();
  }

  applySubFilter() {
    const payload = {
      text: (this.subTextFilter || '').trim().toLowerCase(),
      categoryId: this.subCategoryIdFilter === '' ? null : Number(this.subCategoryIdFilter),
    };
    this.subsDs.filter = JSON.stringify(payload);
    this.subsDs.paginator?.firstPage();
  }

  onProdCategoryChange() {
    // reset sub filter when category changes
    this.prodSubCategoryIdFilter = '';
    this.applyProdFilter();
  }

  applyProdFilter() {
    const payload = {
      text: (this.prodTextFilter || '').trim().toLowerCase(),
      categoryId: this.prodCategoryIdFilter === '' ? null : Number(this.prodCategoryIdFilter),
      subCategoryId: this.prodSubCategoryIdFilter === '' ? null : Number(this.prodSubCategoryIdFilter),
    };
    this.prodsDs.filter = JSON.stringify(payload);
    this.prodsDs.paginator?.firstPage();
  }

  filteredSubCatsForProduct(): SubCategory[] {
    if (this.prodCategoryIdFilter === '') return this.subCategories;
    const catId = Number(this.prodCategoryIdFilter);
    return this.subCategories.filter(s => s.categoryId === catId);
  }

  // ===================== CRUD: CATEGORIES =====================
  newCategory() {
    const ref = this.dialog.open(SimpleNameDialogComponent, {
      width: '420px',
      data: { title: 'New category', nameLabel: 'Category name', name: '' }
    });

    ref.afterClosed().subscribe(v => {
      if (!v?.name) return;
      this.catalog.createCategory(v.name).subscribe({
        next: () => this.reloadAll(),
        error: e => (this.error = e?.error ?? e?.message ?? 'Failed')
      });
    });
  }

  editCategory(c: Category) {
    const ref = this.dialog.open(SimpleNameDialogComponent, {
      width: '420px',
      data: { title: 'Edit category', nameLabel: 'Category name', name: c.name }
    });

    ref.afterClosed().subscribe(v => {
      if (!v?.name) return;
      this.catalog.updateCategory(c.id, v.name).subscribe({
        next: () => this.reloadAll(),
        error: e => (this.error = e?.error ?? e?.message ?? 'Failed')
      });
    });
  }

  deleteCategory(c: Category) {
    const ref = this.dialog.open(ConfirmDialogComponent, {
      width: '420px',
      data: { title: 'Delete category', message: `Delete "${c.name}"?`, confirmText: 'Delete' }
    });

    ref.afterClosed().subscribe(ok => {
      if (!ok) return;
      this.catalog.deleteCategory(c.id).subscribe({
        next: () => this.reloadAll(),
        error: e => (this.error = e?.error ?? e?.message ?? 'Failed')
      });
    });
  }

  // ===================== CRUD: SUB-CATEGORIES =====================
  newSubCategory() {
    const ref = this.dialog.open(SimpleNameDialogComponent, {
      width: '420px',
      data: { title: 'New sub-category', nameLabel: 'Sub-category name', name: '', categoryId: 0, categories: this.categories }
    });

    ref.afterClosed().subscribe(v => {
      if (!v?.name || !v?.categoryId) return;
      this.catalog.createSubCategory(v.name, v.categoryId).subscribe({
        next: () => this.reloadAll(),
        error: e => (this.error = e?.error ?? e?.message ?? 'Failed')
      });
    });
  }

  editSubCategory(s: SubCategory) {
    const ref = this.dialog.open(SimpleNameDialogComponent, {
      width: '420px',
      data: { title: 'Edit sub-category', nameLabel: 'Sub-category name', name: s.name, categoryId: s.categoryId, categories: this.categories }
    });

    ref.afterClosed().subscribe(v => {
      if (!v?.name || !v?.categoryId) return;
      this.catalog.updateSubCategory(s.id, v.name, v.categoryId).subscribe({
        next: () => this.reloadAll(),
        error: e => (this.error = e?.error ?? e?.message ?? 'Failed')
      });
    });
  }

  deleteSubCategory(s: SubCategory) {
    const ref = this.dialog.open(ConfirmDialogComponent, {
      width: '420px',
      data: { title: 'Delete sub-category', message: `Delete "${s.name}"?`, confirmText: 'Delete' }
    });

    ref.afterClosed().subscribe(ok => {
      if (!ok) return;
      this.catalog.deleteSubCategory(s.id).subscribe({
        next: () => this.reloadAll(),
        error: e => (this.error = e?.error ?? e?.message ?? 'Failed')
      });
    });
  }

  // ===================== CRUD: PRODUCTS =====================
  newProduct() {
    const ref = this.dialog.open(ProductEditDialogComponent, {
      width: '720px',
      data: { categories: this.categories, subCategories: this.subCategories }
    });

    ref.afterClosed().subscribe(res => {
      if (!res) return;
      const dto = res.product;

      this.catalog.createProduct(dto).subscribe({
        next: (created: any) => {
          const id = created?.id ?? created?.Id;
          if (id && res.file) {
            this.catalog.uploadProductImage(id, res.file).subscribe({
              next: () => this.reloadAll(),
              error: e => {
                this.error = e?.error ?? e?.message ?? 'Upload failed';
                this.reloadAll();
              }
            });
          } else {
            this.reloadAll();
          }
        },
        error: e => (this.error = e?.error ?? e?.message ?? 'Failed')
      });
    });
  }

  editProduct(p: Product) {
    const ref = this.dialog.open(ProductEditDialogComponent, {
      width: '720px',
      data: { product: p, categories: this.categories, subCategories: this.subCategories }
    });

    ref.afterClosed().subscribe(res => {
      if (!res) return;
      const dto = res.product;

      this.catalog.updateProduct(p.id, dto).subscribe({
        next: () => {
          if (res.file) {
            this.catalog.uploadProductImage(p.id, res.file).subscribe({
              next: () => this.reloadAll(),
              error: e => {
                this.error = e?.error ?? e?.message ?? 'Upload failed';
                this.reloadAll();
              }
            });
          } else {
            this.reloadAll();
          }
        },
        error: e => (this.error = e?.error ?? e?.message ?? 'Failed')
      });
    });
  }

  deleteProduct(p: Product) {
    const ref = this.dialog.open(ConfirmDialogComponent, {
      width: '420px',
      data: { title: 'Delete product', message: `Delete "${p.name}"?`, confirmText: 'Delete' }
    });

    ref.afterClosed().subscribe(ok => {
      if (!ok) return;
      this.catalog.deleteProduct(p.id).subscribe({
        next: () => this.reloadAll(),
        error: e => (this.error = e?.error ?? e?.message ?? 'Failed')
      });
    });
  }

  // ===================== ORDERS =====================
  changeStatus(o: Order, statusId: number) {
    this.ordersSvc.updateStatus(o.id, statusId).subscribe({
      next: () => this.reloadAll(),
      error: e => (this.error = e?.error ?? e?.message ?? 'Failed')
    });
  }

  statusLabel(id: number) {
    return this.statuses.find(s => s.id === id)?.label ?? 'Unknown';
  }

  statusIcon(id: number) {
    return this.statuses.find(s => s.id === id)?.icon ?? 'help';
  }

  statusChipStyle(id: number) {
    switch (id) {
      case 0: return { '--mdc-chip-elevated-container-color': '#fff3cd', '--mdc-chip-label-text-color': '#856404', '--mdc-chip-with-icon-icon-color': '#856404' };
      case 1: return { '--mdc-chip-elevated-container-color': '#d1ecf1', '--mdc-chip-label-text-color': '#0c5460', '--mdc-chip-with-icon-icon-color': '#0c5460' };
      case 2: return { '--mdc-chip-elevated-container-color': '#e2e3ff', '--mdc-chip-label-text-color': '#3f51b5', '--mdc-chip-with-icon-icon-color': '#3f51b5' };
      case 3: return { '--mdc-chip-elevated-container-color': '#d4edda', '--mdc-chip-label-text-color': '#155724', '--mdc-chip-with-icon-icon-color': '#155724' };
      case 4: return { '--mdc-chip-elevated-container-color': '#c3f7d0', '--mdc-chip-label-text-color': '#0f5132', '--mdc-chip-with-icon-icon-color': '#0f5132' };
      case 5: return { '--mdc-chip-elevated-container-color': '#f8d7da', '--mdc-chip-label-text-color': '#721c24', '--mdc-chip-with-icon-icon-color': '#721c24' };
      default: return { '--mdc-chip-elevated-container-color': '#e2e3e5', '--mdc-chip-label-text-color': '#383d41', '--mdc-chip-with-icon-icon-color': '#383d41' };
    }
  }

  viewTicket(o: Order) {
    this.dialog.open(OrderTicketDialogComponent, {
      width: '520px',
      maxWidth: '95vw',
      autoFocus: false,
      restoreFocus: true,
      panelClass: 'ticket-dialog',
      data: { order: o }
    });
  }
}
<div class="page-head">
  <div>
    <h1 class="title">Admin Dashboard</h1>
    <p class="small">Manage catalog and order statuses.</p>
  </div>

  <button mat-raised-button color="primary" (click)="reloadAll()" data-testid="admin-refresh">
    <mat-icon>refresh</mat-icon>
    Refresh
  </button>
</div>

<div *ngIf="loading" class="info">Loading...</div>
<div class="error" *ngIf="error">{{ error }}</div>

<mat-tab-group class="tabs">
  <!-- ===================== CATALOG TAB ===================== -->
  <mat-tab label="Catalog">
    <div class="row">
      <!-- ===================== CATEGORIES ===================== -->
      <div class="col">
        <mat-card class="card">
          <div class="card-head">
            <h3 class="card-title" data-testid="admin-categories-title">Categories</h3>
            <button mat-raised-button color="primary" (click)="newCategory()">
              <mat-icon>add</mat-icon>
              New
            </button>
          </div>

          <div class="filters">
            <mat-form-field appearance="outline" class="w-280">
              <mat-label>Search category</mat-label>
              <input
                matInput
                [(ngModel)]="catFilter"
                (ngModelChange)="applyCatFilter()"
                placeholder="Name..."
              />
              <button
                *ngIf="catFilter"
                matSuffix
                mat-icon-button
                aria-label="Clear"
                (click)="catFilter=''; applyCatFilter()"
              >
                <mat-icon>close</mat-icon>
              </button>
            </mat-form-field>
          </div>

          <div class="table-wrap">
            <table mat-table [dataSource]="catsDs" matSort #catsSort="matSort" class="mat-elevation-z1 full">

              <ng-container matColumnDef="name">
                <th mat-header-cell *matHeaderCellDef mat-sort-header>Name</th>
                <td mat-cell *matCellDef="let c">{{ c.name }}</td>
              </ng-container>

              <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef class="col-actions"></th>
                <td mat-cell *matCellDef="let c" class="col-actions">
                  <button mat-stroked-button (click)="editCategory(c)">Edit</button>
                  <button mat-stroked-button color="warn" (click)="deleteCategory(c)" class="ml-8">Delete</button>
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="catsCols"></tr>
              <tr mat-row *matRowDef="let row; columns: catsCols;"></tr>
            </table>
          </div>

          <mat-paginator
            #catsPaginator
            [pageSize]="8"
            [pageSizeOptions]="[5,8,15,30]"
            showFirstLastButtons>
          </mat-paginator>
        </mat-card>
      </div>

      <!-- ===================== SUB-CATEGORIES ===================== -->
      <div class="col">
        <mat-card class="card">
          <div class="card-head">
            <h3 class="card-title" data-testid="admin-subcategories-title">Sub-categories</h3>
            <button mat-raised-button color="primary" (click)="newSubCategory()" [disabled]="!categories.length">
              <mat-icon>add</mat-icon>
              New
            </button>
          </div>

          <div class="filters">
            <mat-form-field appearance="outline" class="w-260">
              <mat-label>Search</mat-label>
              <input
                matInput
                [(ngModel)]="subTextFilter"
                (ngModelChange)="applySubFilter()"
                placeholder="Name / category..."
              />
              <button
                *ngIf="subTextFilter"
                matSuffix
                mat-icon-button
                aria-label="Clear"
                (click)="subTextFilter=''; applySubFilter()"
              >
                <mat-icon>close</mat-icon>
              </button>
            </mat-form-field>

            <mat-form-field appearance="outline" class="w-260">
              <mat-label>Category</mat-label>
              <mat-select [(ngModel)]="subCategoryIdFilter" (ngModelChange)="applySubFilter()">
                <mat-option [value]="''">All</mat-option>
                <mat-option *ngFor="let c of categories" [value]="c.id">{{ c.name }}</mat-option>
              </mat-select>
            </mat-form-field>
          </div>

          <div class="table-wrap">
            <table mat-table [dataSource]="subsDs" matSort #subsSort="matSort" class="mat-elevation-z1 full">

              <ng-container matColumnDef="name">
                <th mat-header-cell *matHeaderCellDef mat-sort-header>Name</th>
                <td mat-cell *matCellDef="let s">{{ s.name }}</td>
              </ng-container>

              <ng-container matColumnDef="categoryName">
                <th mat-header-cell *matHeaderCellDef mat-sort-header>Category</th>
                <td mat-cell *matCellDef="let s">{{ s.categoryName }}</td>
              </ng-container>

              <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef class="col-actions"></th>
                <td mat-cell *matCellDef="let s" class="col-actions">
                  <button mat-stroked-button (click)="editSubCategory(s)">Edit</button>
                  <button mat-stroked-button color="warn" (click)="deleteSubCategory(s)" class="ml-8">Delete</button>
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="subsCols"></tr>
              <tr mat-row *matRowDef="let row; columns: subsCols;"></tr>
            </table>
          </div>

          <mat-paginator
            #subsPaginator
            [pageSize]="8"
            [pageSizeOptions]="[5,8,15,30]"
            showFirstLastButtons>
          </mat-paginator>
        </mat-card>
      </div>
    </div>

    <!-- ===================== PRODUCTS ===================== -->
    <mat-card class="card mt-12">
      <div class="card-head">
        <h3 class="card-title" data-testid="admin-products-title">Products</h3>
        <button
          mat-raised-button
          color="primary"
          (click)="newProduct()"
          [disabled]="!categories.length || !subCategories.length">
          <mat-icon>add</mat-icon>
          New product
        </button>
      </div>

      <div class="filters">
        <mat-form-field appearance="outline" class="w-280">
          <mat-label>Search</mat-label>
          <input
            matInput
            [(ngModel)]="prodTextFilter"
            (ngModelChange)="applyProdFilter()"
            placeholder="SKU / name / category..."
          />
          <button
            *ngIf="prodTextFilter"
            matSuffix
            mat-icon-button
            aria-label="Clear"
            (click)="prodTextFilter=''; applyProdFilter()"
          >
            <mat-icon>close</mat-icon>
          </button>
        </mat-form-field>

        <mat-form-field appearance="outline" class="w-240">
          <mat-label>Category</mat-label>
          <mat-select [(ngModel)]="prodCategoryIdFilter" (ngModelChange)="onProdCategoryChange()">
            <mat-option [value]="''">All</mat-option>
            <mat-option *ngFor="let c of categories" [value]="c.id">{{ c.name }}</mat-option>
          </mat-select>
        </mat-form-field>

        <mat-form-field appearance="outline" class="w-240">
          <mat-label>Sub-category</mat-label>
          <mat-select [(ngModel)]="prodSubCategoryIdFilter" (ngModelChange)="applyProdFilter()">
            <mat-option [value]="''">All</mat-option>
            <mat-option *ngFor="let s of filteredSubCatsForProduct()" [value]="s.id">{{ s.name }}</mat-option>
          </mat-select>
        </mat-form-field>
      </div>

      <div class="table-wrap">
        <table mat-table [dataSource]="prodsDs" matSort #prodsSort="matSort" class="mat-elevation-z1 full">

          <ng-container matColumnDef="sku">
            <th mat-header-cell *matHeaderCellDef mat-sort-header>SKU</th>
            <td mat-cell *matCellDef="let p">{{ p.sku }}</td>
          </ng-container>

          <ng-container matColumnDef="name">
            <th mat-header-cell *matHeaderCellDef mat-sort-header>Name</th>
            <td mat-cell *matCellDef="let p">{{ p.name }}</td>
          </ng-container>

          <ng-container matColumnDef="categoryName">
            <th mat-header-cell *matHeaderCellDef mat-sort-header>Category</th>
            <td mat-cell *matCellDef="let p">{{ p.categoryName }}</td>
          </ng-container>

          <ng-container matColumnDef="subCategoryName">
            <th mat-header-cell *matHeaderCellDef mat-sort-header>Sub</th>
            <td mat-cell *matCellDef="let p">{{ p.subCategoryName }}</td>
          </ng-container>

          <ng-container matColumnDef="price">
            <th mat-header-cell *matHeaderCellDef mat-sort-header>Price</th>
            <td mat-cell *matCellDef="let p">{{ p.price | number:'1.2-2' }}</td>
          </ng-container>

          <ng-container matColumnDef="stockQty">
            <th mat-header-cell *matHeaderCellDef mat-sort-header>Stock</th>
            <td mat-cell *matCellDef="let p">{{ p.stockQty }}</td>
          </ng-container>

          <ng-container matColumnDef="actions">
            <th mat-header-cell *matHeaderCellDef class="col-actions"></th>
            <td mat-cell *matCellDef="let p" class="col-actions">
              <button mat-stroked-button (click)="editProduct(p)">Edit</button>
              <button mat-stroked-button color="warn" (click)="deleteProduct(p)" class="ml-8">Delete</button>
            </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="prodsCols"></tr>
          <tr mat-row *matRowDef="let row; columns: prodsCols;"></tr>
        </table>
      </div>

      <mat-paginator
        #prodsPaginator
        [pageSize]="10"
        [pageSizeOptions]="[5,10,20,50]"
        showFirstLastButtons>
      </mat-paginator>
    </mat-card>
  </mat-tab>

  <!-- ===================== ORDERS TAB (unchanged) ===================== -->
  <mat-tab label="Orders">
    <mat-card class="card mt-12">
      <div class="table-wrap">
        <table class="plain">
          <thead>
            <tr>
              <th>#</th>
              <th>User</th>
              <th>Date</th>
              <th>Status</th>
              <th>Total</th>
              <th style="width:240px;">Change status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let o of orders">
              <td>{{ o.id }}</td>
              <td>{{ o.username }}</td>
              <td>{{ o.createdAtUtc | date:'short' }}</td>
              <td>
                <mat-chip class="status-chip" [ngStyle]="statusChipStyle(o.status)">
                  <mat-icon class="status-icon">{{ statusIcon(o.status) }}</mat-icon>
                  {{ statusLabel(o.status) }}
                </mat-chip>
              </td>
              <td>{{ o.total | number:'1.2-2' }}</td>
              <td>
                <mat-select style="width:220px;" [ngModel]="o.status" (ngModelChange)="changeStatus(o,$event)">
                  <mat-option *ngFor="let s of statuses" [value]="s.id">
                    <mat-icon style="margin-right:6px;vertical-align:middle;">{{ s.icon }}</mat-icon>
                    {{ s.label }}
                  </mat-option>
                </mat-select>
              </td>
              <td>
                <button mat-stroked-button (click)="viewTicket(o)">
                  <mat-icon>receipt_long</mat-icon>
                  Ticket
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </mat-card>
  </mat-tab>
</mat-tab-group>
