// frontend/ecom-ui/src/app/shared/dashboard-widgets/kpi-cards.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { Kpi } from 'src/app/core/services/dashboard.service';

@Component({
  selector: 'app-kpi-cards',
  standalone: true,
  imports: [CommonModule, MatCardModule],
  template: `
  <div class="kpi-grid" *ngIf="kpis?.length">
    <mat-card class="kpi" *ngFor="let k of kpis">
      <div class="label">{{ k.label }}</div>
      <div class="value">{{ format(k.value, k.unit) }}</div>
    </mat-card>
  </div>
  `,
  styles: [`
    .kpi-grid{display:grid;grid-template-columns:repeat(6,minmax(140px,1fr));gap:12px;align-items:stretch}
    .kpi{padding:12px}
    .label{font-size:12px;opacity:.75}
    .value{font-size:22px;font-weight:700;margin-top:6px;line-height:1.1}
    @media (max-width:1200px){.kpi-grid{grid-template-columns:repeat(3,minmax(140px,1fr));}}
    @media (max-width:700px){.kpi-grid{grid-template-columns:repeat(2,minmax(140px,1fr));}}
  `]
})
export class KpiCardsComponent {
  @Input() kpis: Kpi[] | null = null;

  format(v: number, unit?: string | null): string {
    if (unit === '%') return `${v.toFixed(1)}%`;
    if (unit === 'days') return `${v.toFixed(1)} days`;
    if (unit === '$') return this.money(v);
    if (!unit) return this.compact(v);
    return `${this.compact(v)} ${unit}`;
  }

  private money(v: number): string {
    return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(v);
  }
  private compact(v: number): string {
    return new Intl.NumberFormat(undefined, { notation: 'compact', maximumFractionDigits: 1 }).format(v);
  }
}

// frontend/ecom-ui/src/components/dashboard/KpiCards.tsx
import React from 'react';
import './KpiCards.css';

export interface Kpi {
  label: string;
  value: number;
  unit: string | null;
}

const formatValue = (v: number, unit?: string | null): string => {
  if (unit === '%') return `${v.toFixed(1)}%`;
  if (unit === 'days') return `${v.toFixed(1)} days`;
  if (unit === '$') return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(v);
  
  const compact = new Intl.NumberFormat(undefined, { notation: 'compact', maximumFractionDigits: 1 }).format(v);
  if (!unit) return compact;
  return `${compact} ${unit}`;
};

export const KpiCards = ({ kpis }: { kpis: Kpi[] | null }) => {
  if (!kpis || !kpis.length) return null;

  return (
    <div className="kpi-grid">
      {kpis.map((k, i) => (
        <div key={i} className="kpi">
          <div className="kpi-icon">
            <span className="material-icons">bar_chart</span>
          </div>
          <div>
            <div className="label">{k.label}</div>
            <div className="value">{formatValue(k.value, k.unit)}</div>
          </div>
        </div>
      ))}
    </div>
  );
};
